import Header from "./Header";
import BackToTopButton from "./BackToTopButton";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

//export const metadata: Metadata = {
  //title: "Lakshani Parami - Portfolio",
  //description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/girl.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBn5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="relative z-50">
          <Header />
        </header>
        <main className="grow p-4">{children}</main>
        <BackToTopButton />
        <footer className="p-4 bg-gray-800 text-white mt-8">
          <div className="container mx-auto flex justify-between items-center">
            <div className="text-left">
              <p>&copy; {new Date().getFullYear()} LakshaniParami. All rights reserved.</p>
            </div>
            <div className="text-right flex space-x-4">
              <a href="https://github.com/lakshanirathnayaka" target="_blank" rel="noopener noreferrer" className="hover:text-blue-400 text-2xl">
                <i className="fab fa-github"></i>
              </a>
              <a href="https://linkedin.com/in/lakshani-parami-rathnayaka" target="_blank" rel="noopener noreferrer" className="hover:text-blue-400 text-2xl">
                <i className="fab fa-linkedin"></i>
              </a>
              <a href="mailto:lakshanirathnayaka124@gmail.com" className="hover:text-blue-400 text-2xl">
                <i className="fas fa-envelope"></i>
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
