import Header from "./Header";
import BackToTopButton from "./BackToTopButton";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faGithub, faLinkedin } from '@fortawesome/free-brands-svg-icons';
import { faEnvelope } from '@fortawesome/free-solid-svg-icons';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

//export const metadata: Metadata = {
  //title: "Lakshani Parami - Portfolio",
  //description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  config.autoAddCss = false;
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/girl.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="relative z-50">
          <Header />
        </header>
        <main className="bg-black grow p-4">{children}</main>
        <BackToTopButton />
        <footer className="p-4 bg-black text-white mt-8">
          <div className="container mx-auto flex justify-between items-center">
            <div className="text-left">
              <p>&copy; {new Date().getFullYear()} LakshaniParami. All rights reserved.</p>
            </div>
            <div className="text-right flex space-x-4 text-white">
              <a href="https://github.com/lakshanirathnayaka" target="_blank" rel="noopener noreferrer" className="text-white hover:text-blue-400 text-2xl">
                <FontAwesomeIcon icon={faGithub} className="w-6 h-6" />
              </a>
              <a href="https://linkedin.com/in/lakshani-parami-rathnayaka" target="_blank" rel="noopener noreferrer" className="text-white hover:text-blue-400 text-2xl">
                <FontAwesomeIcon icon={faLinkedin} className="w-6 h-6" />
              </a>
              <a href="mailto:lakshanirathnayaka124@gmail.com" className="text-white hover:text-blue-400 text-2xl">
                <FontAwesomeIcon icon={faEnvelope} className="w-6 h-6" />
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
